// <auto-generated />
namespace Skillset_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changemanagercode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changemanagercode));
        
        string IMigrationMetadata.Id
        {
            get { return "201803231029115_change manager code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
