// <auto-generated />
namespace Skillset_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newSkills : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newSkills));
        
        string IMigrationMetadata.Id
        {
            get { return "201804021204420_newSkills"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
